### ISSUE TITLE
Sint Eustatius flag should be renamed to BQ-SE

### ISSUE THREAD

**Issue by jeroenvisser101** [hiddevdploeg/SEOshop-Flags#2]
According to ISO 3166-2: https://en.wikipedia.org/wiki/ISO_3166-2:BQ

(mainly because colliding with Sweden's SE language code)

**Comment by jeroenvisser101** [comment]
I also suggest we use ISO 3166-2 for this as it also has country codes for Scotland, Lichtenstein and most of the flags in _other.

**Comment by hiddevdploeg** [comment]
Thanks, will pick this up later this week
